### ISSUE TITLE
Fix axis for qualplot in newer versions of matplotlib

### ISSUE THREAD

**Issue by mdshw5** [mdshw5/fastqp#34]
```
Traceback (most recent call last):
  File "/usr/prog/scicomp/pythonds/v1.0/pyds_v1.0/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/prog/scicomp/pythonds/v1.0/pyds_v1.0/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/da/onc/BFx/pisces/0.1.5.3/src/novartis-pisces/pisces/__init__.py", line 135, in read_level_qc
    run(arguments)
  File "/da/onc/BFx/pisces/0.1.5.3/lib/python3.8/site-packages/fastqp/cli.py", line 341, in run
    qualplot(positions, quantiles, zip_archive, fig_kw)
  File "/da/onc/BFx/pisces/0.1.5.3/lib/python3.8/site-packages/fastqp/plots.py", line 311, in qualplot
    ax.yaxis.grid(b=True, which='major', **{'color': 'gray', 'linestyle': ':'})
  File "/da/onc/BFx/pisces/0.1.5.3/lib/python3.8/site-packages/matplotlib/axis.py", line 1698, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/da/onc/BFx/pisces/0.1.5.3/lib/python3.8/site-packages/matplotlib/axis.py", line 944, in set_tick_params
    kwtrans = self._translate_tick_params(kwargs)
  File "/da/onc/BFx/pisces/0.1.5.3/lib/python3.8/site-packages/matplotlib/axis.py", line 1088, in _translate_tick_params
    raise ValueError(
ValueError: keyword grid_b is not recognized; valid keywords are ['size', 'width', 'color', 'tickdir', 'pad', 'labelsize', 'labelcolor', 'zorder', 'gridOn', 'tick1On', 'tick2On', 'label1On', 'label2On', 'length', 'direction', 'left', 'bottom', 'right', 'top', 'labelleft', 'labelbottom', 'labelright', 'labeltop', 'labelrotation', 'grid_agg_filter', 'grid_alpha', 'grid_animated', 'grid_antialiased', 'grid_clip_box', 'grid_clip_on', 'grid_clip_path', 'grid_color', 'grid_dash_capstyle', 'grid_dash_joinstyle', 'grid_dashes', 'grid_data', 'grid_drawstyle', 'grid_figure', 'grid_fillstyle', 'grid_gapcolor', 'grid_gid', 'grid_in_layout', 'grid_label', 'grid_linestyle', 'grid_linewidth', 'grid_marker', 'grid_markeredgecolor', 'grid_markeredgewidth', 'grid_markerfacecolor', 'grid_markerfacecoloralt', 'grid_markersize', 'grid_markevery', 'grid_mouseover', 'grid_path_effects', 'grid_picker', 'grid_pickradius', 'grid_rasterized', 'grid_sketch_params', 'grid_snap', 'grid_solid_capstyle', 'grid_solid_joinstyle', 'grid_transform', 'grid_url', 'grid_visible', 'grid_xdata', 'grid_ydata', 'grid_zorder', 'grid_aa', 'grid_c', 'grid_ds', 'grid_ls', 'grid_lw', 'grid_mec', 'grid_mew', 'grid_mfc', 'grid_mfcalt', 'grid_ms']
```

**Comment by mdshw5** [comment]
https://github.com/matplotlib/matplotlib/issues/25267

**Comment by mdshw5** [comment]
Pushed a fix to the master branch. Working on #35 before testing and pushing a new package version.
